env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-runtime/recommended
  - plugin:jsx-a11y/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jsx/a11y
rules: { react/self-closing-comp: warn }
